# Generated by Django 5.2 on 2025-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('contato', models.IntegerField()),
                ('secao', models.IntegerField(max_length=3)),
                ('cadeiras', models.IntegerField(max_length=3)),
                ('filme', models.CharField()),
            ],
        ),
    ]
