# Generated by Django 5.2 on 2025-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('nome_completo', models.CharField(max_length=150)),
                ('contato', models.IntegerField(primary_key=True, serialize=False)),
                ('filme', models.CharField(max_length=150)),
                ('secao', models.IntegerField()),
                ('cadeira', models.IntegerField()),
            ],
        ),
    ]
